#!/bin/bash

LOCALPATH="`dirname \"$0\"`"
cd $LOCALPATH

if [ -z "$*" ]; then
	LINE=$(shuf -n 1 motivationals.txt)
else
	LINE=$(head -$* motivationals.txt | tail -1)
fi

IFS=, read SUSILANG SUSITEXT <<< "$LINE"

echo "Susi says ($SUSILANG): $SUSITEXT"
TTSLANG=$SUSILANG ./tts-emit "$SUSITEXT"
